version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: url-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: url-redis
    ports:
      - "6379:6379"